export const projects = [
  {
    title: "ONOW Web APP(PWA)",
    imgSrc: "/project-img/onow-pwa.png",
    description:
      "This is a learning application that includes Myanmar and English language. This is a private project.",
    techStack: [
      "PWA",
      "React",
      "Next JS",
      "Material UI",
      "React Saga",
      "Redux",
      "localization",
      "Responsive",
      "axios",
      "authentication",
    ],
    // link: "https://project2.com",
    // github: "https://github.com/yourusername/project2",
  },

  {
    title: "ONOW CMS",
    imgSrc: "/project-img/onow-cms.png",
    description:
      "This is a content management system (CMS). This product was developed by design tokens. Changes made to the design in Figma automatically update the frontend through a token-based UI system. This is a private project.",
    techStack: [
      "React",
      "Next JS",
      "Material UI",
      "Design tokens",
      "React Saga",
      "Redux",
      "Redux toolkit",
      "authentication",
      "axios",
    ],
    // link: "https://project2.com",
    // github: "https://github.com/yourusername/project2",
  },
  {
    title: "Duwun",
    imgSrc: "/project-img/duwun.png",
    description:
      "This is a entertainment website that includes articles and videos.",
    techStack: [
      "React",
      "Next JS",
      "Material UI",
      "React Saga",
      "Redux",
      "express JS",
      "axios",
      "responsive",
    ],
    link: "https://www.duwun.com.mm/",
  },
  {
    title: "Duwun Beta PWA",
    imgSrc: "/project-img/onow-cms.png",
    description:
      "This is a entertainment progressive web app. This is a private project.",
    techStack: ["Vue", "Pwa", "vuetify"],
    isBlur: true,
  },
  {
    title: "Own project1 (Basic Bootstrap template) ",
    imgSrc: "/project-img/bootstrap-template.png",
    description: "This is a simple bootstrap template.",
    techStack: [
      "HTML",
      "css",
      "javascript",
      "jquery",
      "bootstrap",
      "animate css",
      "owl-carousel",
    ],
    link: "https://basic-bootstrap-template-henna.vercel.app/",
    github: "https://github.com/developer-maythinn/bootstrap-template",
  },
  {
    title: "Own project2 (Basic template)",
    imgSrc: "/project-img/html-sass-template.png",
    description: "This is a simple template.",
    techStack: ["HTML", "sass", "animate css"],
    link: "https://simple-html-scss-template.vercel.app/",
    github: "https://github.com/developer-maythinn/simple-html-scss-template",
  },
];
